Slices/config/routes.rb
Rails.application.routes.draw do
  resources :slices

  root 'slices#new'
end

Slices/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Slices/app/models/slice.rb
class Slice < ApplicationRecord


end

Slices/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Slices/app/controllers/slices_controller.rb
class SlicesController < ApplicationController
  def show
    @slice = Slice.find(params[:id])
  end

  def new
    @slice = Slice.new
  end

  def create
    @slice = Slice.new(params.permit(:season, :collections))
    @slice.save
    p @slice
    # redirect_to @slice
  #   if @slice.save
  #     redirect_to @slice
  #   else
  #     render 'new'
  #   end
  end


end

Slices/app/helpers/application_helper.rb
module ApplicationHelper
end

Slices/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Slices</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

Slices/app/views/slices/new.html.erb
<%= form_with scope: :slices, url: slices_path, local: true do |form| %>
  <p>
    <%= form.label :season %><br>
    <%= form.text_field :season %>
  </p>

  <p>
    <%= form.label :collections %><br>
    <%= form.text_area :collections %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

Slices/app/views/slices/show.html.erb
<p>
  <strong>season:</strong>
  <%= @slice.season %>
</p>

<p>
  <strong>collections:</strong>
  <%= @slice.collections %>
</p>